language: python
python:
  - 2.6
  - 2.7

install:
  - pip install pep8 --use-mirrors
#  - pip install pyflakes --use-mirrors
# - pip install coveralls

before_script:
  - "pep8 --exclude=minjson.py --ignore=E501 ."
#  - pyflakes -x W .

script:
    - PYTHONPATH=.:${PYTHONPATH} nosetests

#after_success:
#    coveralls

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false
