sudo: required
language: python
python:
  - 2.7

conditions: v1

cache:
  directories:
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION.9
    - vendor/cache
    - $CACHE_DIR
  timeout: 1000
matrix:
  fast_finish: true
  include:
    - os: osx
      language: generic
      python:
      env: TRAVIS_FLAVOR=default

services:
  - docker

env:
  global:
    - CONCURRENCY=2
    - NOSE_FILTER="not windows"
    - INTEGRATIONS_DIR=$HOME/embedded
    - CHECKSD_OVERRIDE=$TRAVIS_BUILD_DIR/tests/checks/fixtures/checks
    - PIP_CACHE=$HOME/.cache/pip
    - VOLATILE_DIR=/tmp
    - DD_CASHER_DIR=/tmp/casher
    - AGENT_VERSION=2.2.3
    - CACHE_DIR=$HOME/.cache
    - CACHE_FILE_el6=$CACHE_DIR/el6.tar.gz
    - CACHE_FILE_el6_i386=$CACHE_DIR/el6_i386.tar.gz
    - CACHE_FILE_el7=$CACHE_DIR/el7.tar.gz
    - CACHE_FILE_bionic=$CACHE_DIR/bionic.tar.gz
    - CACHE_FILE_jessie=$CACHE_DIR/jessie.tar.gz
    - CACHE_FILE_stretch=$CACHE_DIR/stretch.tar.gz
    - CACHE_FILE_trusty=$CACHE_DIR/trusty.tar.gz
    - CACHE_FILE_xenial=$CACHE_DIR/xenial.tar.gz
  matrix:
    - TRAVIS_FLAVOR=default
    - TRAVIS_FLAVOR=checks_mock

matrix:
  include:
    - python: 2.7
      sudo: required
      services: docker
      env: TRAVIS_FLAVOR=core_integration

# Override travis defaults with empty jobs
before_install:
- rvm install 2.1.5
# before_install: echo "OVERRIDING TRAVIS STEPS"
install: echo "OVERRIDING TRAVIS STEPS"
before_script: echo "OVERRIDING TRAVIS STEPS"

script:
  - ./.travis/build_installer.sh

before_install: echo "OVERRIDING TRAVIS STEPS"
install: echo "OVERRIDING TRAVIS STEPS"
before_script:
  - if [ "${TRAVIS_OS_NAME}" != "osx" ]; then sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static createrepo reprepro; fi
  - if [ "${TRAVIS_OS_NAME}" != "osx" ]; then echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register; fi
script: travis_retry ./.travis/build_installer.sh
after_failure:
  - echo "Logs from installation process come here / DEBUG LOGS"
  - cat /tmp/ci.log

notifications:
  slack:
    secure: EIK5M4WH0/ZnwgCyd6T4801Ll9g9pQuxmkL5PVCCzUHeT2ouwxFepEA/2olb74DYUc1DiDbhlKyevxZVw9l6G2vwZY670N9ZAhbivyDjK6hOduIt8+YicJNtFs3PzilRpu9yPrpDFlrOeuT8MT1TMP8xTCfvDa6WDic2Nfen4L0=

jobs:
  include:
    - stage: build containers
      script: travis_retry ./.travis/build_containers.sh
      python: 2.7
      env: RELEASE=bionic
    - stage: build containers
      script: travis_retry ./.travis/build_containers.sh
      python: 2.7
      env: RELEASE=jessie
    - stage: build containers
      script: travis_retry ./.travis/build_containers.sh
      python: 2.7
      env: RELEASE=xenial
    - stage: build containers
      script: travis_retry ./.travis/build_containers.sh
      python: 2.7
      env: RELEASE=stretch
    - stage: build containers
      script: travis_retry ./.travis/build_containers.sh
      python: 2.7
      env: RELEASE=trusty
    - stage: build containers
      script: travis_retry ./.travis/build_containers.sh
      python: 2.7
      env: RELEASE=el6
    - stage: build containers
      script: travis_retry ./.travis/build_containers.sh
      python: 2.7
      env: RELEASE=el6_i386
    - stage: build containers
      script: travis_retry ./.travis/build_containers.sh
      python: 2.7
      env: RELEASE=el7
    - stage: build packages
      script: travis_retry ./.travis/build_packages.sh
      env: RELEASE=bionic
      python: 2.7
      deploy:
      - provider: gcs
        access_key_id: "GOOGQSTXHRV5ODGTXK2GT4U4"
        secret_access_key:
            secure: EyTxi3GZOlwGmYT0eld3copYEGLoymOo2ZO7jXkUa4bVmdbSpUHokYAVip6r+zf42tfKhzr1S2GWPDKhF/AozYX9ZOtvzojK92RGmwp6B1n1JIKWgqHE91LaIArp1i+sPk4ACe6dann1N7KKXcjyCNXXjjaw9RHogNHp2muc9vQ=
        bucket: "sd-agent-packages"
        skip_cleanup: true
        acl: public-read
        local-dir: /serverdensity
        on:
          all_branches: true
    - stage: build packages
      script: travis_retry ./.travis/build_packages.sh
      env: RELEASE=jessie
      python: 2.7
      deploy:
      - provider: gcs
        access_key_id: "GOOGQSTXHRV5ODGTXK2GT4U4"
        secret_access_key:
            secure: EyTxi3GZOlwGmYT0eld3copYEGLoymOo2ZO7jXkUa4bVmdbSpUHokYAVip6r+zf42tfKhzr1S2GWPDKhF/AozYX9ZOtvzojK92RGmwp6B1n1JIKWgqHE91LaIArp1i+sPk4ACe6dann1N7KKXcjyCNXXjjaw9RHogNHp2muc9vQ=
        bucket: "sd-agent-packages"
        skip_cleanup: true
        acl: public-read
        local-dir: /serverdensity
        on:
          all_branches: true
    - stage: build packages
      script: travis_retry ./.travis/build_packages.sh
      env: RELEASE=xenial
      python: 2.7
      deploy:
      - provider: gcs
        access_key_id: "GOOGQSTXHRV5ODGTXK2GT4U4"
        secret_access_key:
            secure: EyTxi3GZOlwGmYT0eld3copYEGLoymOo2ZO7jXkUa4bVmdbSpUHokYAVip6r+zf42tfKhzr1S2GWPDKhF/AozYX9ZOtvzojK92RGmwp6B1n1JIKWgqHE91LaIArp1i+sPk4ACe6dann1N7KKXcjyCNXXjjaw9RHogNHp2muc9vQ=
        bucket: "sd-agent-packages"
        skip_cleanup: true
        acl: public-read
        local-dir: /serverdensity
        on:
          all_branches: true
    - stage: build packages
      script: travis_retry ./.travis/build_packages.sh
      env: RELEASE=stretch
      python: 2.7
      deploy:
      - provider: gcs
        access_key_id: "GOOGQSTXHRV5ODGTXK2GT4U4"
        secret_access_key:
            secure: EyTxi3GZOlwGmYT0eld3copYEGLoymOo2ZO7jXkUa4bVmdbSpUHokYAVip6r+zf42tfKhzr1S2GWPDKhF/AozYX9ZOtvzojK92RGmwp6B1n1JIKWgqHE91LaIArp1i+sPk4ACe6dann1N7KKXcjyCNXXjjaw9RHogNHp2muc9vQ=
        bucket: "sd-agent-packages"
        skip_cleanup: true
        acl: public-read
        local-dir: /serverdensity
        on:
          all_branches: true
    - stage: build packages
      script: travis_retry ./.travis/build_packages.sh
      env: RELEASE=trusty
      python: 2.7
      deploy:
      - provider: gcs
        access_key_id: "GOOGQSTXHRV5ODGTXK2GT4U4"
        secret_access_key:
            secure: EyTxi3GZOlwGmYT0eld3copYEGLoymOo2ZO7jXkUa4bVmdbSpUHokYAVip6r+zf42tfKhzr1S2GWPDKhF/AozYX9ZOtvzojK92RGmwp6B1n1JIKWgqHE91LaIArp1i+sPk4ACe6dann1N7KKXcjyCNXXjjaw9RHogNHp2muc9vQ=
        bucket: "sd-agent-packages"
        skip_cleanup: true
        acl: public-read
        local-dir: /serverdensity
        on:
          all_branches: true
    - stage: build packages
      script: travis_retry ./.travis/build_packages.sh
      env: RELEASE=el6
      python: 2.7
      deploy:
      - provider: gcs
        access_key_id: "GOOGQSTXHRV5ODGTXK2GT4U4"
        secret_access_key:
            secure: EyTxi3GZOlwGmYT0eld3copYEGLoymOo2ZO7jXkUa4bVmdbSpUHokYAVip6r+zf42tfKhzr1S2GWPDKhF/AozYX9ZOtvzojK92RGmwp6B1n1JIKWgqHE91LaIArp1i+sPk4ACe6dann1N7KKXcjyCNXXjjaw9RHogNHp2muc9vQ=
        bucket: "sd-agent-packages"
        skip_cleanup: true
        acl: public-read
        local-dir: /serverdensity
        on:
          all_branches: true
    - stage: build packages
      script: travis_retry ./.travis/build_packages.sh
      env: RELEASE=el6_i386
      python: 2.7
      deploy:
      - provider: gcs
        access_key_id: "GOOGQSTXHRV5ODGTXK2GT4U4"
        secret_access_key:
            secure: EyTxi3GZOlwGmYT0eld3copYEGLoymOo2ZO7jXkUa4bVmdbSpUHokYAVip6r+zf42tfKhzr1S2GWPDKhF/AozYX9ZOtvzojK92RGmwp6B1n1JIKWgqHE91LaIArp1i+sPk4ACe6dann1N7KKXcjyCNXXjjaw9RHogNHp2muc9vQ=
        bucket: "sd-agent-packages"
        skip_cleanup: true
        acl: public-read
        local-dir: /serverdensity
        on:
          all_branches: true
    - stage: build packages
      script: travis_retry ./.travis/build_packages.sh
      env: RELEASE=el7
      python: 2.7
      deploy:
      - provider: gcs
        access_key_id: "GOOGQSTXHRV5ODGTXK2GT4U4"
        secret_access_key:
            secure: EyTxi3GZOlwGmYT0eld3copYEGLoymOo2ZO7jXkUa4bVmdbSpUHokYAVip6r+zf42tfKhzr1S2GWPDKhF/AozYX9ZOtvzojK92RGmwp6B1n1JIKWgqHE91LaIArp1i+sPk4ACe6dann1N7KKXcjyCNXXjjaw9RHogNHp2muc9vQ=
        bucket: "sd-agent-packages"
        skip_cleanup: true
        acl: public-read
        local-dir: /serverdensity
        on:
          all_branches: true
    - os: osx
      language: generic
      python:
      env: TRAVIS_FLAVOR=default
      deploy:
      - provider: gcs
        access_key_id: "GOOGQSTXHRV5ODGTXK2GT4U4"
        secret_access_key:
            secure: EyTxi3GZOlwGmYT0eld3copYEGLoymOo2ZO7jXkUa4bVmdbSpUHokYAVip6r+zf42tfKhzr1S2GWPDKhF/AozYX9ZOtvzojK92RGmwp6B1n1JIKWgqHE91LaIArp1i+sPk4ACe6dann1N7KKXcjyCNXXjjaw9RHogNHp2muc9vQ=
        bucket: "sd-agent-packages"
        skip_cleanup: true
        acl: public-read
        local-dir: /serverdensity
        on:
          all_branches: true
